[package]
name = "hello_world_rust"
version = "0.1.0"
edition = "2021"
authors = ["Carmelo Ricarte Rocamora"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt = "0.1.0"
